language: objective-c
sudo: false
osx_image: xcode8.3

matrix:
  include:
    - os: osx
      env: ACTION=test_ios10
    - os: osx
      env: ACTION=test_ios9

script:
  - bundle exec fastlane $ACTION
