osx_image: xcode61

language: objective-c

before_install:
  - gem install xcpretty --no-document --quiet
  - gem install cocoapods --no-document --quiet
  - cd EasyMappingExample
  - export LANG=en_US.UTF-8
    
script: rake
